name: 'Pull request reviewer reminder'
on:
  schedule:
    - cron: '5 * * * 1-5'

jobs:
  pull-request-reviewer-reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: tommykw/pull-request-reviewer-reminder-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reminder_message: 'レビュー開始から1営業日経過しました。レビューをなるべく優先しましょう。'
          review_turnaround_hours: 0.1
